// Generated by gencpp from file test_roslib/message1.msg
// DO NOT EDIT!


#ifndef TEST_ROSLIB_MESSAGE_MESSAGE1_H
#define TEST_ROSLIB_MESSAGE_MESSAGE1_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_roslib
{
template <class ContainerAllocator>
struct message1_
{
  typedef message1_<ContainerAllocator> Type;

  message1_()
    : robot()
    , x(0.0)
    , y(0.0)
    , th(0.0)  {
    }
  message1_(const ContainerAllocator& _alloc)
    : robot(_alloc)
    , x(0.0)
    , y(0.0)
    , th(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robot_type;
  _robot_type robot;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _th_type;
  _th_type th;





  typedef boost::shared_ptr< ::test_roslib::message1_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_roslib::message1_<ContainerAllocator> const> ConstPtr;

}; // struct message1_

typedef ::test_roslib::message1_<std::allocator<void> > message1;

typedef boost::shared_ptr< ::test_roslib::message1 > message1Ptr;
typedef boost::shared_ptr< ::test_roslib::message1 const> message1ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_roslib::message1_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_roslib::message1_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test_roslib::message1_<ContainerAllocator1> & lhs, const ::test_roslib::message1_<ContainerAllocator2> & rhs)
{
  return lhs.robot == rhs.robot &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.th == rhs.th;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test_roslib::message1_<ContainerAllocator1> & lhs, const ::test_roslib::message1_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test_roslib

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::test_roslib::message1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_roslib::message1_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_roslib::message1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_roslib::message1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_roslib::message1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_roslib::message1_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_roslib::message1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dff9bfd755bfc63a3ec938fa82a872cb";
  }

  static const char* value(const ::test_roslib::message1_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdff9bfd755bfc63aULL;
  static const uint64_t static_value2 = 0x3ec938fa82a872cbULL;
};

template<class ContainerAllocator>
struct DataType< ::test_roslib::message1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_roslib/message1";
  }

  static const char* value(const ::test_roslib::message1_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_roslib::message1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string robot\n"
"float32 x\n"
"float32 y\n"
"float32 th\n"
;
  }

  static const char* value(const ::test_roslib::message1_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_roslib::message1_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.th);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct message1_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_roslib::message1_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_roslib::message1_<ContainerAllocator>& v)
  {
    s << indent << "robot: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robot);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "th: ";
    Printer<float>::stream(s, indent + "  ", v.th);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_ROSLIB_MESSAGE_MESSAGE1_H
