// Generated by gencpp from file test_roslib/Service1Request.msg
// DO NOT EDIT!


#ifndef TEST_ROSLIB_MESSAGE_SERVICE1REQUEST_H
#define TEST_ROSLIB_MESSAGE_SERVICE1REQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_roslib
{
template <class ContainerAllocator>
struct Service1Request_
{
  typedef Service1Request_<ContainerAllocator> Type;

  Service1Request_()
    : robot()
    , x(0.0)
    , y(0.0)
    , th(0.0)  {
    }
  Service1Request_(const ContainerAllocator& _alloc)
    : robot(_alloc)
    , x(0.0)
    , y(0.0)
    , th(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robot_type;
  _robot_type robot;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _th_type;
  _th_type th;





  typedef boost::shared_ptr< ::test_roslib::Service1Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_roslib::Service1Request_<ContainerAllocator> const> ConstPtr;

}; // struct Service1Request_

typedef ::test_roslib::Service1Request_<std::allocator<void> > Service1Request;

typedef boost::shared_ptr< ::test_roslib::Service1Request > Service1RequestPtr;
typedef boost::shared_ptr< ::test_roslib::Service1Request const> Service1RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_roslib::Service1Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_roslib::Service1Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test_roslib::Service1Request_<ContainerAllocator1> & lhs, const ::test_roslib::Service1Request_<ContainerAllocator2> & rhs)
{
  return lhs.robot == rhs.robot &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.th == rhs.th;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test_roslib::Service1Request_<ContainerAllocator1> & lhs, const ::test_roslib::Service1Request_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test_roslib

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::test_roslib::Service1Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_roslib::Service1Request_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_roslib::Service1Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_roslib::Service1Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_roslib::Service1Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_roslib::Service1Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_roslib::Service1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ae6bc460c0fd52c233a3c99d36cb4b9e";
  }

  static const char* value(const ::test_roslib::Service1Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xae6bc460c0fd52c2ULL;
  static const uint64_t static_value2 = 0x33a3c99d36cb4b9eULL;
};

template<class ContainerAllocator>
struct DataType< ::test_roslib::Service1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_roslib/Service1Request";
  }

  static const char* value(const ::test_roslib::Service1Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_roslib::Service1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string robot\n"
"float64 x\n"
"float64 y\n"
"float64 th\n"
;
  }

  static const char* value(const ::test_roslib::Service1Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_roslib::Service1Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.th);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Service1Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_roslib::Service1Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_roslib::Service1Request_<ContainerAllocator>& v)
  {
    s << indent << "robot: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robot);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "th: ";
    Printer<double>::stream(s, indent + "  ", v.th);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_ROSLIB_MESSAGE_SERVICE1REQUEST_H
